use_frameworks!

platform :ios, '9.0'

target 'ZKComponentThree_Example' do
  pod 'ZKComponentThree', :path => '../'

  target 'ZKComponentThree_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
